# Generated by Django 5.0.6 on 2024-07-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
